# Generated by Django 3.2.5 on 2022-08-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220810_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='个人简介'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gexing',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='个性签名'),
        ),
    ]
